# Site settings
title: 1Percenter Blog
email: blog@1percenter.com
description: "Roben Kleene's blog version 3 or 4 or whatever, the time when he <i>really</i> gets it right."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: redcarpet
permalink: pretty
