# Site settings
title: Roben Kleene
email: roben@1percenter.com
description: "Roben Kleene's blog version 3 or 4 or whatever, the time when he really gets it right."
baseurl: ""
url: "http://blog.robenkleene.com"
twitter_username: robenkleene
github_username: robenkleene

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# theme: minima
remote_theme: robenkleene/cyclist

plugins:
  - jekyll-feed

# theme
# show_excerpts: true
show_contents: true

permalink: /:year/:month/:day/:title/
